/*
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
*/

var localizedStrings = {
    "Balance": "Guthaben",
    "Email:": "Email:",
    "enter login data": "Benutzerdaten eingeben",
    "EUR": "€",
    "Fertig": "Fertig",
    "Hallo Welt!": "Hallo Welt!",
    "letters": "Zeichen",
    "logged in": "Login erfolgreich",
    "login failed": "Login fehlgeschlagen",
    "Password:": "Passwort:",
    "Price": "Preis",
    "SMS sender help": "Make sure this number was validated on the sipgate website before. If left empty the sender will be \"sipgate\".",
    "Username:": "Username:"
};
