/*
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
*/

var localizedStrings = {
    "Balance": "Guthaben",
    "Email:": "Email:",
    "enter login data": "Benutzerdaten eingeben",
    "EUR": "€",
    "Fertig": "Fertig",
    "Hallo Welt!": "Hallo Welt!",
    "letters": "Zeichen",
    "logged in": "Login erfolgreich",
    "login failed": "Login fehlgeschlagen",
    "Password:": "Passwort:",
    "Price": "Preis",
    "sending failed": "senden fehlgeschlagen",
    "sipgate credentials:": "sipgate Zugangsdaten:",
    "SMS sender help": "Stellen Sie sicher, dass diese Nummer auf der sipgate Seite validiert wurde!",
    "Username:": "Username:"
};
